// flow-typed signature: 333a735d1a60fdd2d4c9a29cce90dcfc
// flow-typed version: <<STUB>>/fs_v0.0.1-security/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs' {
  declare module.exports: any;
}
