// flow-typed signature: ce2f376144aea33ff6c0607b3b2dc1af
// flow-typed version: <<STUB>>/is-image_v^2.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-image/index' {
  declare module.exports: $Exports<'is-image'>;
}
declare module 'is-image/index.js' {
  declare module.exports: $Exports<'is-image'>;
}
