// flow-typed signature: 2652b0d35b7f2318ffcb099756be8646
// flow-typed version: <<STUB>>/resize-img_v^1.1.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resize-img'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resize-img' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'resize-img/index' {
  declare module.exports: $Exports<'resize-img'>;
}
declare module 'resize-img/index.js' {
  declare module.exports: $Exports<'resize-img'>;
}
